#!/bin/bash

# usage: ./replacenames <new icon file> <apk>

ICON_FILE=$1
APK=$2
APK_BASENAME=`basename $APK .apk`

echo "decompiling apk..."
apktool/apktool d $APK > /dev/null

echo "replacing icons..."
# TODO: generate proper dpi aware sizes or whatever
find $APK_BASENAME -name wine.png -exec cp $ICON_FILE {} \;

echo "rebuilding apk..."
apktool/apktool b $APK_BASENAME -o $APK_BASENAME-unsigned.apk > /dev/null

echo "signing..."
dex-tools-2.1/d2j-apk-sign.sh -f -o $APK_BASENAME.apk $APK_BASENAME-unsigned.apk

rm $APK_BASENAME-unsigned.apk
rm -rf $APK_BASENAME