#!/bin/bash

# usage: ./send <ip of device> <version to send, patched, debug, vanilla...> <package>

ADB="`pwd`/android/platform-tools/adb"

echo "$ADB"

"$ADB" connect $1
"$ADB" uninstall org.winehq.wine > /dev/null 2>&1
"$ADB" push -p wine-$2.apk /data/local/tmp
"$ADB" shell pm install /data/local/tmp/wine-$2.apk
"$ADB" shell rm /data/local/tmp/wine-$2.apk
"$ADB" shell am start -n $3/.WineActivity
"$ADB" disconnect